- 👋 Hi, I’m Zainab Eman
- 👀 I’m interested in Web development, Web design, and Artificial Intelligence.
- 🌱 I’m currently doing Bachelors in Software Engineering.
- 💞️ I’m working on my Web Development skills.
- 📫 You can reach me at my email zainabeman976@gmail.com.
